// search index for WYSIWYG Web Builder
var database_length = 0;

function SearchPage(url, title, keywords, description)
{
   this.url = url;
   this.title = title;
   this.keywords = keywords;
   this.description = description;
   return this;
}

function SearchDatabase()
{
   database_length = 0;
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/index.php", "The Third Eye Creation", "We serve all over the pan asia  SERVICES  Services offered by Third Eye Creation starting from the pre-wedding to the wedding and post wedding function,\"TEC\" offers you with mind-blowing videos and pictures of your best moments with perfection and skills We complete wedding and other ceremony video within a day The wide range of services are  Photo booth  •Model shoot •Bridal shoots •Pre-wedding shoot •Post-wedding shoot • Engagement Photography •  Music video shoot •Music video shoot • Drone shots • Maternity shoot •Baby shoot •Rice ceremony shoot •Baby shower shoot •Outdoor shoot •Product Shoot • Candid photography •Fashion photography shoot •Cinematic Videos • Any types of editing • Advertisement Shoot • Live screening • Architectural photography shoot •Albums Your wish, Our commitment  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  Happy Customers  Photo Shoots  Ceremony Cover  Videography Shoot  Video Editing  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/video.php", "Video", "© Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  Contact us  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/gallery.php", "Gallery", "© Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  Contact us  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/contactus.php", "Contact us", "#We complete shoot and video editing before the ceremony end   9933448052  7063515775   terms and conditions apply  SERVICES  Services offered by Third Eye Creation starting from the pre-wedding to the wedding and post wedding function,\"TEC\" offers you with mind-blowing videos and pictures of your best moments with perfection and skills We complete wedding and other ceremony video within a day The wide range of services are  Photo booth  •Model shoot •Bridal shoots •Pre-wedding shoot •Post-wedding shoot • Engagement Photography •  Music video shoot •Music video shoot • Drone shots • Maternity shoot •Baby shoot •Rice ceremony shoot •Baby shower shoot •Outdoor shoot •Product Shoot • Candid photography •Fashion photography shoot •Cinematic Videos • Any types of editing • Advertisement Shoot • Live screening • Architectural photography shoot •Albums Your wish, Our commitment   © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  Happy Customers  Photo Shoots  Ceremony Cover  Videography Shoot  Video Editing  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/booknow.php", "Book Now", "We serve all over the pan asia  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  SERVICES  Services offered by Third Eye Creation starting from the pre-wedding to the wedding and post wedding function,\"TEC\" offers you with mind-blowing videos and pictures of your best moments with perfection and skills We complete wedding and other ceremony video within a day The wide range of services are  Photo booth  •Model shoot •Bridal shoots •Pre-wedding shoot •Post-wedding shoot • Engagement Photography •  Music video shoot •Music video shoot • Drone shots • Maternity shoot •Baby shoot •Rice ceremony shoot •Baby shower shoot •Outdoor shoot •Product Shoot • Candid photography •Fashion photography shoot •Cinematic Videos • Any types of editing • Advertisement Shoot • Live screening • Architectural photography shoot •Albums Your wish, Our commitment   Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/about.php", "About Third Eye Creation", "We serve all over the pan asia  THIRD EYE CREATION  The Third Eye Creation, a renowned wedding and videography company based in Suburbs of Kolkata city They have an expert teams of photographers,videographers and editors who aims to provide you the best services covering all over India The esteemed team of The Third Eye Creation uses high definition equipment and the latest technologies to give you the perfect shot  In a sentence, it's the one stop solution to all your worries  Our Team  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  Happy Customers  Photo Shoots  Ceremony Cover  Videography Shoot  Video Editing  Follow Us  SERVICES  Services offered by Third Eye Creation starting from the pre-wedding to the wedding and post wedding function,\"TEC\" offers you with mind-blowing videos and pictures of your best moments with perfection and skills We complete wedding and other ceremony video within a day The wide range of services are  Photo booth  •Model shoot •Bridal shoots •Pre-wedding shoot •Post-wedding shoot • Engagement Photography •  Music video shoot •Music video shoot • Drone shots • Maternity shoot •Baby shoot •Rice ceremony shoot •Baby shower shoot •Outdoor shoot •Product Shoot • Candid photography •Fashion photography shoot •Cinematic Videos • Any types of editing • Advertisement Shoot • Live screening • Architectural photography shoot •Albums Your wish, Our commitment   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/feedback.php", "Feedback", "We serve all over the pan asia  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/Career.php", "Career", "We serve all over the pan asia  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/404.php", "The Third Eye Creation", "We serve all over the pan asia  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  No Content Found ￼  Follow Us   ", "");
   this[database_length++] = new SearchPage("https://www.thethirdeyecreation.com/page1.php", "The Third Eye Creation", "We serve all over the pan asia  Contact us  © Copyright 2021 Third Eye Creation  Designed & Developed by Kaustav Roy  #We complete shoot and video editing before the ceremony end  Follow Us   ", "");
   return this;
}
